### ISSUE TITLE
The uploaded plugin archive does not contain a folder that corresponds to the plugin name.

### ISSUE THREAD

**Issue by ghost** [pkp/tinymce#16]
I searched for this plugin from the dashboard but could not find it. So, I downloaded the zip version of this repo and tried to upload it on OJS3.0.2 but it keeps on saying "Notification: The uploaded plugin archive does not contain a folder that corresponds to the plugin name." I tried uploading the zip file, no luck. I then extracted it and uploaded. No luck again. I changed the name of the zip and folder inside of it. Again no luck. I then changed the name of the extracted folder from "tinymce-master" to "tinymce". No luck again. I guess this plugin is not supported in OJS 3.0.2? Or i did something wrong? Please help me on this. Thank you.

**Comment by bozana** [comment]
@aacsssh, this plugin should be integrated in the OJS 3.0.2. Could you please double check, if you have it under Settings > Website > Plugins > Generic Plugins > TinyMCE Plugin. Also could you could you double check on your server if there is a folder plugins/generic/tinymce/ ? If it does not exist, how did you install OJS 3.0.2?

**Comment by ghost** [comment]
@bozana Thank you for your time. I looked at the folder you mentioned and it was empty. I added the files and folder of Tinymce that I downloaded from Github. There are some other empty folders in plugins/generic folder. I don't know how it happened.

I have installed OJS3.0.2 from Github by cloning it, then switching to ojs3_0_2-stable branch. After that, I updated the composer from 'lib/pkp'. One thing to note is that there was no composer.json and I added it later myself.  I may have screwed on the way but, as far as I remember I followed all the instructions for the update and I didn't receive any error while doing it. Anyway, thank you.

**Comment by bozana** [comment]
maybe you have forgotten to do something like: git submodule update --init --recursive? plugins/generic/tinymce is a submodule... as some others are...

**Comment by ghost** [comment]
@bozana  I have definitely not done that. Where is that thing mentioned? Thank you for helping me out. I really appreciate it.

**Comment by bozana** [comment]
No problem, you're welcome! :-)
I will have to see if there is another documentation, but for now, maybe this helps. https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors ?
