### ISSUE TITLE
ALM for OJS 2.4.8

### ISSUE THREAD

**Issue by gkmnarslan** [pkp/tinymce#21]
Hello,
How can I install the ALM plugin for OJS 2.4.8 (www.journalppw.com?
I used the Install A New Plugin, yet did not install. 

Thanks in advance.

**Comment by bozana** [comment]
Hi @gkmnarslan 

Have you search for that subject in the PKP forum: https://forum.pkp.sfu.ca/? That would be the place to look for... Thus closing this issue here...
