### ISSUE TITLE
maybe registerJSData never used

### ISSUE THREAD

**Issue by forgive38** [pkp/tinymce#56]
Hi

It seems that registerJSLibraryData never used because corresponding call  
https://github.com/pkp/pkp-lib/blob/14f8c88d4744da272dd0dea5c65935c52c001ed8/classes/template/PKPTemplateManager.inc.php#L715

is called only one time (when Template Manager is first initialized) and before all plugins are registered.

(ojs 3.1.2
I saw that because I just want to add charmap plugin to tinyMCE
By the way, the use of Wysiwyg editor is very usefull, thank you !
)

Thank you

**Comment by NateWr** [comment]
This was removed in OJS 3.2 (probably for this reason, thought I can't recall exactly why). See this commit: https://github.com/pkp/pkp-lib/commit/a09aa46d196539078b29ae8426a1384d86147d2a#diff-a52d1f134c8e119d3cdb2e280b60ac82

Now, if you want to add data to the pkp namespace, you should do the following:

```js
$templateMgr = TemplateManager::getManager($request);
$templateMgr->addJavaScript(
	'myCustomJS',
	'$.pkp.plugins.myCustomPlugin.anyData = "something";',
	[
		'priority' => STYLE_SEQUENCE_CORE,
		'contexts' => 'backend',
		'inline'   => true,
	]
);
```

There's a real-life use-case here in the [tinymce plugin](https://github.com/pkp/tinymce/blob/master/TinyMCEPlugin.inc.php#L77-L99).
